// Regenerate interop/vectors/vectors.json — the normative canonicalisation and signature-encoding
// test data for ADR-014.
//
//   node interop/generate.mjs          write vectors/vectors.json + vectors/VECTORS.sha256
//   node interop/generate.mjs --check  verify the committed files match, emit nothing (CI mode)
//
// TRUST MODEL. The vectors are generated by the `canonicalize` npm package, so on its own this file
// would only prove "the estate agrees with one library". It does not stop there: before emitting a
// single byte, the generator asserts that its canonicaliser reproduces RFC 8785's OWN published test
// data (Appendix B) exactly. A canonicaliser that fails that assertion cannot write vectors. So the
// file is anchored to the RFC, and swapping the generator's dependency for any other conformant
// implementation must produce a byte-identical result.
//
// The signature vectors use a FIXED P-256 keypair whose private key is committed in plain text. That
// is deliberate and safe: it exists so that every implementation verifies the same bytes with the
// same key. It is a published test key. It must never appear in any deployed configuration, and CI
// greps for it outside this directory.
import canonicalize from "canonicalize";
import { createHash, sign as cryptoSign, verify as cryptoVerify, createSign } from "node:crypto";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = join(HERE, "vectors");
const OUT_VECTORS = join(OUT_DIR, "vectors.json");
const OUT_SHA = join(OUT_DIR, "VECTORS.sha256");

const C = String.fromCharCode;   // build control characters by code point, never by escape
const sha256hex = (s) => createHash("sha256").update(s, "utf8").digest("hex");
const jcs = (v) => {
  const out = canonicalize(v);
  if (typeof out !== "string") throw new Error("canonicalization returned a non-string");
  return out;
};

// ---------------------------------------------------------------------------
// Gate: the generator must reproduce RFC 8785's published test data, or it does not run.
// ---------------------------------------------------------------------------
// Every vector's input is read as RAW TEXT from vectors/inputs/, never as a parsed value.
//
// This is not a style choice. The first draft of this file held inputs as JavaScript objects and
// wrote them into the manifest with JSON.stringify, which silently normalised `500.0` to `500` and
// `-0` to `0` — destroying the exact distinctions two of the vectors exist to test. The vectors
// still passed, because both sides of the comparison had been normalised the same way. Only
// verify_catches.py caught it, by reporting that a vector claiming to detect the Python
// canonicaliser no longer did.
//
// JSON has one number type; the difference between 500.0 and 500 lives only in the text. So the
// text is what is authored, committed, and shipped in the manifest.
const INPUT_DIR = join(OUT_DIR, "inputs");
const readInput = (id) => readFileSync(join(INPUT_DIR, `${id}.json`), "utf8");

// Gate: the generator must reproduce RFC 8785's published test data, or it does not run.
const RFC_INPUT = JSON.parse(readInput("01-rfc8785-appendix-b"));
const RFC_EXPECTED = readFileSync(join(OUT_DIR, "rfc8785-appendix-b.expected.txt"), "utf8");

if (jcs(RFC_INPUT) !== RFC_EXPECTED) {
  console.error("REFUSING TO EMIT — the canonicaliser does not reproduce RFC 8785 Appendix B.");
  console.error("  got      : " + jcs(RFC_INPUT));
  console.error("  expected : " + RFC_EXPECTED);
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Canonicalisation vectors.
//
// `catches` names the implementations each vector is known to fail, measured 5-6 August 2026:
//   ts-localecompare — the ~8-line replacer copied into all four h2a TS references and Bridle core
//   py-json-dumps    — reference/h2a_ref/verify.py:28, json.dumps(sort_keys=True)
// A vector with an empty `catches` is a regression guard, not an indictment.
// ---------------------------------------------------------------------------
const VECTORS = [
  {
    id: "01-rfc8785-appendix-b",
    why: "RFC 8785's own published test data. Anchors this file to the RFC rather than to any library. If an implementation fails only this vector, its number or escape handling is broken.",
    catches: ["py-json-dumps"],
  },
  {
    id: "02-unicode-subject-name",
    why: "A performer whose name carries diacritics. RFC 8785 §3.2.2.2 emits characters above U+001F as literal UTF-8; Python's json.dumps defaults to ensure_ascii=True and escapes them, so the two disagree on a completely ordinary grant.",
    catches: ["py-json-dumps"],
  },
  {
    id: "03-lease-cap-decimal",
    why: "A lease cap authored as 500.0 rather than 500. ECMAScript Number::toString emits 500; Python's repr emits 500.0. Same number, different bytes, invalid signature.",
    catches: ["py-json-dumps"],
  },
  {
    id: "04-mixed-case-keys",
    why: "Sorting must compare UTF-16 code units as unsigned integers (RFC 8785 §3.2.3: 'independent of locale settings'). localeCompare collates case-insensitively and puts 'alpha' before 'Beta'; JCS puts every uppercase key first.",
    catches: ["ts-localecompare"],
  },
  {
    id: "05-integer-like-keys",
    why: "The subtlest of the four. A canonicaliser that sorts entries and then rebuilds a JavaScript object loses the sort: integer-like keys are re-ordered to the front in numeric order on insertion. JCS requires '10' < '2' by code unit. Emit from the sorted sequence, never via an object.",
    catches: ["ts-localecompare"],
  },
  {
    id: "06-nesting-null-empty",
    why: "Structural regression guard: nested objects inside arrays must be sorted too, empty arrays and objects must survive, and null must not be confused with an object by a truthiness test.",
    catches: [],
  },
  {
    id: "07-control-characters",
    why: "RFC 8785 §3.2.2.2: U+0000-U+001F use lowercase \\uhhhh except the five with short forms (\\b \\t \\n \\f \\r). Only quote and backslash are escaped above that range.",
    catches: [],
  },
  {
    id: "08-number-forms",
    why: "Number serialisation across the awkward range: integral floats, negative zero (JCS emits 0, Python emits -0.0), exponent thresholds, and the largest integer that survives a double.",
    catches: ["py-json-dumps"],
  },
  {
    id: "09-grant-signing-preimage",
    why: "ADR-014 §3. The preimage for a detached grant signature is the grant with the `signatures` member REMOVED, not emptied. This vector is that preimage; every signer in the estate must derive these exact bytes before signing.",
    catches: ["ts-localecompare", "py-json-dumps"],
  },
];

// ---------------------------------------------------------------------------
// Signature-encoding vectors (ADR-014 §2).
// ---------------------------------------------------------------------------
const TEST_PRIVATE_KEY_PEM =
  "-----BEGIN PRIVATE KEY-----\n" +
  "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgTVXMSBVAxcyub3Xv\n" +
  "elQQ7JKlFy6E69Xg+5h4JCdLv8qhRANCAARCeWvBwYd6SWpEowIRiB2d8NfULV7N\n" +
  "ax1a+Z7eOZHZazyBsePbf1O/PBkrZsQqdiezafXGL5TaCXQ2A+QehBTc\n" +
  "-----END PRIVATE KEY-----\n";
const TEST_PUBLIC_KEY_PEM =
  "-----BEGIN PUBLIC KEY-----\n" +
  "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQnlrwcGHeklqRKMCEYgdnfDX1C1e\n" +
  "zWsdWvme3jmR2Ws8gbHj239TvzwZK2bEKnYns2n1xi+U2gl0NgPkHoQU3A==\n" +
  "-----END PUBLIC KEY-----\n";

// ECDSA is randomised, so a signature's bytes cannot be regenerated deterministically. The committed
// signature below is therefore fixed once and only re-derived if it fails to verify — otherwise
// `--check` could never be stable. What IS deterministic, and what the vector actually asserts, is
// that a conformant verifier accepts the raw form and a DER-defaulted one does not.
const SIG_MESSAGE_INPUT_JSON = readInput("10-signature-preimage");
const SIG_PREIMAGE = jcs(JSON.parse(SIG_MESSAGE_INPUT_JSON));

let rawSigB64u;
try {
  const existing = JSON.parse(readFileSync(OUT_VECTORS, "utf8"));
  rawSigB64u = existing.signature_vectors?.signature_raw_r_s_base64url;
} catch { /* first run */ }

const verifiesRaw = (b64u) =>
  !!b64u &&
  cryptoVerify("sha256", Buffer.from(SIG_PREIMAGE, "utf8"),
    { key: TEST_PUBLIC_KEY_PEM, dsaEncoding: "ieee-p1363" }, Buffer.from(b64u, "base64url"));

if (!verifiesRaw(rawSigB64u)) {
  rawSigB64u = cryptoSign("sha256", Buffer.from(SIG_PREIMAGE, "utf8"),
    { key: TEST_PRIVATE_KEY_PEM, dsaEncoding: "ieee-p1363" }).toString("base64url");
}

const rawBuf = Buffer.from(rawSigB64u, "base64url");
if (rawBuf.length !== 64) throw new Error(`raw R||S must be 64 bytes, got ${rawBuf.length}`);

// The same signature re-encoded as DER — what Node's createSign and AWS KMS return, and what every
// pre-ADR-014 implementation in the estate emitted.
const toDerInt = (b) => {
  let v = b;
  while (v.length > 1 && v[0] === 0) v = v.subarray(1);
  if (v[0] & 0x80) v = Buffer.concat([Buffer.from([0]), v]);
  return Buffer.concat([Buffer.from([0x02, v.length]), v]);
};
const r = toDerInt(rawBuf.subarray(0, 32));
const s = toDerInt(rawBuf.subarray(32, 64));
const derBuf = Buffer.concat([Buffer.from([0x30, r.length + s.length]), r, s]);

// Prove the cross-acceptance claim rather than restating it.
const derDefaultAcceptsDer = createSign; // referenced to keep the import honest
void derDefaultAcceptsDer;
const acceptance = {
  der_verifier_accepts_der: cryptoVerify("sha256", Buffer.from(SIG_PREIMAGE, "utf8"), TEST_PUBLIC_KEY_PEM, derBuf),
  der_verifier_accepts_raw: cryptoVerify("sha256", Buffer.from(SIG_PREIMAGE, "utf8"), TEST_PUBLIC_KEY_PEM, rawBuf),
  raw_verifier_accepts_raw: verifiesRaw(rawSigB64u),
  raw_verifier_accepts_der: cryptoVerify("sha256", Buffer.from(SIG_PREIMAGE, "utf8"),
    { key: TEST_PUBLIC_KEY_PEM, dsaEncoding: "ieee-p1363" }, derBuf),
};
if (acceptance.der_verifier_accepts_raw || acceptance.raw_verifier_accepts_der) {
  throw new Error("the two encodings are unexpectedly cross-compatible — re-derive this vector");
}

// ---------------------------------------------------------------------------
// Emit.
// ---------------------------------------------------------------------------
const manifest = {
  $comment:
    "NORMATIVE test data for ADR-014. Generated by interop/generate.mjs; do not hand-edit. " +
    "An implementation is conformant iff it reproduces every `canonical` value byte-for-byte from " +
    "the corresponding `input`, emits 64-byte raw R||S signatures, and reproduces the acceptance " +
    "matrix below. Vector 01 is RFC 8785's own published test data.",
  adr: "ADR-014-canonical-form",
  spec: "RFC 8785 JSON Canonicalization Scheme",
  generated_from_rfc_appendix_b: true,
  canonicalization_vectors: VECTORS.map((v) => {
    const inputJson = readInput(v.id);
    const canonical = jcs(JSON.parse(inputJson));
    return {
      id: v.id,
      why: v.why,
      catches: v.catches,
      // The authored bytes. Implementations MUST parse this string rather than reading a
      // pre-parsed value, or they inherit their host language's number normalisation and the
      // vector silently stops testing what it names.
      input_json: inputJson,
      canonical,
      canonical_sha256: sha256hex(canonical),
      canonical_utf8_bytes: Buffer.byteLength(canonical, "utf8"),
    };
  }),
  signature_vectors: {
    $comment:
      "PUBLISHED TEST KEY — the private key is committed on purpose so every implementation can " +
      "verify identical bytes. Never deploy it. ADR-014 §2: alg:'ES256' is raw R||S, never DER.",
    alg: "ES256",
    curve: "P-256",
    private_key_pem: TEST_PRIVATE_KEY_PEM,
    public_key_pem: TEST_PUBLIC_KEY_PEM,
    preimage_input_json: SIG_MESSAGE_INPUT_JSON,
    preimage_canonical: SIG_PREIMAGE,
    preimage_sha256: sha256hex(SIG_PREIMAGE),
    signature_raw_r_s_base64url: rawSigB64u,
    signature_raw_byte_length: rawBuf.length,
    signature_same_signature_as_der_base64url: derBuf.toString("base64url"),
    signature_der_byte_length: derBuf.length,
    acceptance_matrix: acceptance,
  },
};

const json = JSON.stringify(manifest, null, 2) + "\n";
const digest = sha256hex(json);
const shaFile =
  "# sha256 of the normative vector file. S1.X1 vendors interop/vectors/ into three CIs by this\n" +
  "# digest, so a silent edit to the vectors fails every downstream build rather than passing them.\n" +
  "#   sha256sum -c VECTORS.sha256      (run from interop/vectors/)\n" +
  `${digest}  vectors.json\n`;

if (process.argv.includes("--check")) {
  const onDisk = readFileSync(OUT_VECTORS, "utf8");
  if (onDisk !== json) {
    console.error("MISMATCH — vectors.json is not what generate.mjs produces. Re-run without --check.");
    process.exit(1);
  }
  if (readFileSync(OUT_SHA, "utf8") !== shaFile) {
    console.error("MISMATCH — VECTORS.sha256 does not match vectors.json.");
    process.exit(1);
  }
  console.log(`vectors.json matches the generator (sha256 ${digest.slice(0, 16)}...)`);
  console.log(`${manifest.canonicalization_vectors.length} canonicalisation vectors + signature vectors verified`);
} else {
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(OUT_VECTORS, json, "utf8");
  writeFileSync(OUT_SHA, shaFile, "utf8");
  console.log(`wrote ${manifest.canonicalization_vectors.length} canonicalisation vectors + signature vectors`);
  console.log(`sha256(vectors.json) = ${digest}`);
}
